[build-system]
build-backend = "setuptools.build_meta"
requires = ['setuptools', 'extreqs']

[project]
name = 'abn_assignment'
requires-python = ">=3.11"
version = "0.1.0"

[tool.black]
line-length = 88
