name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: abnamro_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e . 
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Test
      run: |
        pytest
      env:
        FLASK_APP: = abn_assignment.api
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_NAME: abnamro_test